### ISSUE TITLE
Add an interface for the email message data

### ISSUE THREAD

**Issue by bambooch** [zeforgezenica/busez#116]
https://github.com/bambooch/busez/blob/1152978c7ce29f16a867cff41b5c049cd2f7e2b8/frontend/src/app/components/Footer.tsx#L39

**Comment by Aman4017** [comment]
@bambooch assign me under hacktoberfest.

**Comment by bambooch** [comment]
There you go @Aman4017 

below is the link to the existing interface so you can just connect that to the referenced part of code

https://github.com/morascode/busez/blob/366b7ba2c9b9d60b27b1d7ac5655c0eb1c6ffabb/frontend/src/app/services/email.service.ts#L3
