### ISSUE TITLE
Automatically Detect User's Location

### ISSUE THREAD

**Issue by alempasalic** [zeforgezenica/busez#119]
Building upon the existing feature request [#118](https://github.com/zeforgezenica/busez/issues/118), which aims to add support for tracking bus transit data in more countries and cities, I propose an additional feature to automatically detect the user's location. This enhancement will enable the app to provide localized transit data without requiring the user to manually input their location.

**Comment by alempasalic** [comment]
We could also automatically detect the station at which the user is in with the upcoming [Maps features](https://github.com/zeforgezenica/busez/pull/96)

**Comment by morascode** [comment]
@alempasalic I have opened a PR for this issue: #126.
