### ISSUE TITLE
Rewrite handleFilterRoutes() methodRefactor `handleFilterRoutes()` Method to Improve Code Maintainability

### ISSUE THREAD

**Issue by vrosi21** [zeforgezenica/busez#127]
The `handleFilterRoutes()` method in the `HomePage` component is currently too large and handles multiple filtering operations, making it difficult to maintain and understand. We need to refactor this method to improve code readability and maintainability. 

### Proposed Changes:
1. **Single Responsibility**: Refactor `handleFilterRoutes()` to perform a single filtering operation. This means breaking down the current method into multiple smaller methods, each handling a specific filter criterion.
2. **Create `FilterService`**: Introduce a new `FilterService` to manage all filtering logic. This service will have multiple functions or subfunctions, each dedicated to a particular filter type. This separation will improve modularity and make the code easier to test and extend.
3. **Update `HomePage`**: Modify the `HomePage` component to utilize the new `FilterService` and its methods, ensuring that the filtering logic is cleanly abstracted away from the UI component.

### Benefits:
- **Improved Readability**: Smaller, single-purpose methods are easier to read and understand.
- **Enhanced Maintainability**: Isolating filtering logic in a `FilterService` makes future modifications and bug fixes easier.
- **Better Testability**: Unit tests can be written for each filtering method individually, ensuring robust and reliable code.

### Acceptance Criteria:
- `handleFilterRoutes()` method is refactored into multiple smaller methods.
- A new `FilterService` is created with methods for filtration.
- The `HomePage` component is updated to use the `FilterService`.

**Comment by thryngabriel** [comment]
Hey, I'll take a look at this if you assign me and no one's working on it yet

**Comment by bambooch** [comment]
sure @thryngabriel I'll assign you
