### ISSUE TITLE
Establish Basis for Unit and Integration Testing

### ISSUE THREAD

**Issue by vrosi21** [zeforgezenica/busez#138]
**Description**:

We need to set up a foundation for unit and integration testing for our project. Initially, this will involve creating tests for backend routes, providing a framework that we can extend and upgrade for future automated testing.

### Objectives:
1. **Setup Testing Framework**:
   - Integrate a testing framework like Jest, Mocha, or similar.
   - Configure the framework to work with our existing project structure.

2. **Create Initial Test Cases**:
   - Write basic unit tests for key functions.
   - Develop integration tests to verify the functionality of backend routes.

3. **Document Testing Procedures**:
   - Provide clear instructions on how to run the tests.
   - Outline the structure for adding new tests in the future.

### Benefits:
- Establish a reliable basis for testing our code.
- Ensure backend routes function correctly.
- Facilitate future development of comprehensive automated tests.
- Enhance code quality and maintainability.

### Acceptance Criteria:
- Testing framework is set up and configured.
- Initial unit and integration tests are created and passing.
- Documentation is provided to guide new contributors on testing procedures.

**Comment by Aman4017** [comment]
@vrosi21, assign me this issue.

**Comment by bambooch** [comment]
@Aman4017 I'll assign you, just make sure to make a new branch on your fork before opening a PR
