### ISSUE TITLE
Napraviti rješenje za prikaz stanice na mapi / Solution to display bus stations on a map

### ISSUE THREAD

**Issue by bambooch** [zeforgezenica/busez#62]
**ENGLISH**

The problem we are trying to solve is the ambiguity of stations, people usually don't know what the name of the station is and displaying the station as a pin on a map would solve this issue.

**BOSANSKI**

Problem koji pokušavamo riješiti je nejasnost oko stanica. Ljudi obično ne znaju kako se stanica zove, a prikazivanje stanice kao oznake na mapi bi riješilo ovaj problem.

**Comment by bambooch** [comment]
@vrosi21

**Comment by vrosi21** [comment]
Eo
