### ISSUE TITLE
Add contrast to dates in dark date picker

### ISSUE THREAD

**Issue by bambooch** [zeforgezenica/busez#81]
The datepicker dates are hard to see as seen on the screenshot below

![image](https://github.com/user-attachments/assets/c12e4d41-90eb-4a81-a828-99123a7d2b07)

**Comment by NechamaSopher** [comment]
@bambooch Hi, I will love to do this, Can you please assign me?

**Comment by bambooch** [comment]
> @bambooch Hi, I will love to do this, Can you please assign me?

hi @NechamaSopher sure, but if you'll do this please then do #83 as well since this is a subtask of the UI facelift we're doing now for the project (converting all of this to shadcn/ui components)

**Comment by bambooch** [comment]
@NechamaSopher please leave a comment on #83 also so I can assign you there if that is okay :)

**Comment by NechamaSopher** [comment]
Hi, I'm on it. still not finished...

**Comment by anandanshul** [comment]
I would love to work on this issue

**Comment by bambooch** [comment]
> I would love to work on this issue

@anandanshul thanks for taking an interest! I'm afraid that we need to give @NechamaSopher at least a week before considering someone else. 

feel free to take up another issue or perhaps find some new ones, if you need any guidance, please reach out! once more thanks for taking the time to consider contributing :D

**Comment by NechamaSopher** [comment]
@bambooch Hi, is this ok or should I make some changes?
![image](https://github.com/user-attachments/assets/ff30312d-aa1e-4e62-8e34-d2ad88a4cb8b)

**Comment by bambooch** [comment]
@NechamaSopher perfect! Thanks! feel free to open a PR whenever you like :D

**Comment by NechamaSopher** [comment]
@bambooch It looks like someone added yesterday DateSelector.tsx component, Do I need to change that to mine?

**Comment by bambooch** [comment]
@NechamaSopher afaik there was no work done on the date selector except yours, probably it is some refactor or generated & unused code

feel free to replace it while merging

**Comment by NechamaSopher** [comment]
@bambooch Thank you, I created a pr. DateSelector component could be deleted.
