### ISSUE TITLE
Convert station selection comboboxes to shadcn/ui

### ISSUE THREAD

**Issue by bambooch** [zeforgezenica/busez#82]
There are two combobox components on the main page, the start station selection

![image](https://github.com/user-attachments/assets/8353aa67-d76b-4015-88e9-7252017afebe)

![image](https://github.com/user-attachments/assets/09c40874-387c-4723-ba3b-59599a777757)

and the end station selection

![image](https://github.com/user-attachments/assets/b58db492-437c-49b4-aff0-a3101fcdd2ae)

![image](https://github.com/user-attachments/assets/76274dfb-52ae-42c6-8918-655e0941fae4)

They should be converted to shadcn/ui combobox component, reference below:

https://ui.shadcn.com/docs/components/combobox

**Comment by thryngabriel** [comment]
Hey, could I be assigned this if no one else is working on it yet?

**Comment by bambooch** [comment]
Hey @thryngabriel sure, thanks for taking an interest! I've assigned you the issue :D
