### ISSUE TITLE
Convert datepicker to shadcn/ui component

### ISSUE THREAD

**Issue by bambooch** [zeforgezenica/busez#83]
There is 1 datepicker that needs to be converted:

![image](https://github.com/user-attachments/assets/1009bb96-10bf-4a52-9ceb-cf83475250fb)

![image](https://github.com/user-attachments/assets/0fc7c5c0-ae39-49a3-99ef-7a37b69c18be)

Issue #81 is linked to this as well so if you take this one please take that one as well 

Reference:
https://ui.shadcn.com/docs/components/date-picker

**Comment by hemangtk** [comment]
Hey @bambooch  could you please explain the issue in detail so i that i can start working on it right away

**Comment by bambooch** [comment]
> Hey @bambooch could you please explain the issue in detail so i that i can start working on it right away

@hemangtk well the idea is to just replace the current datepicker (which is material ui I believe) with the shadcn/ui component as stated in the reference above. please let me know if I should assign you, I'll also assign you to #81 then since it's essentially a subtask for this

**Comment by NechamaSopher** [comment]
@bambooch Hi, Can you please assign me to this as well?

**Comment by bambooch** [comment]
> @bambooch Hi, Can you please assign me to this as well?

@NechamaSopher done, thank you!

@hemangtk sorry, @NechamaSopher was first though on issue #81 so I've assigned them to this one

feel free to comment on some other issue (#82 #85 #84) are all similar to this one

**Comment by hemangtk** [comment]
Hey @bambooch not a problem at all 
will go through the issues and comment there!!
thank you!!
